// apps/demo-vue/app/plugin-demos/nativescript-label-marquee.vue
<template>
  <Page>
    <ActionBar>
      <Label text="nativescript-label-marquee"/>
    </ActionBar>

    <GridLayout>
      <Button class="info" :text="message"/>
    </GridLayout>
  </Page>
</template>

<script lang="ts">
  import Vue from "nativescript-vue";
  import { DemoSharedNativescriptLabelMarquee } from '@demo/shared';
  import { } from '@ignacio68/nativescript-label-marquee';

  export default Vue.extend({
    computed: {
      message() {
        return "Test nativescript-label-marquee";
      }
    }
  });
</script>

<style scoped lang="scss">

  .info {
    font-size: 20;
    horizontal-align: center;
    vertical-align: center;
  }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-label-marquee.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptLabelMarquee } from '@demo/shared';
import {} from '@ignacio68/nativescript-label-marquee';

@Component({
  selector: 'demo-nativescript-label-marquee',
  templateUrl: 'nativescript-label-marquee.component.html',
})
export class NativescriptLabelMarqueeComponent {
  demoShared: DemoSharedNativescriptLabelMarquee;

  constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptLabelMarquee();
  }
}

<ActionBar title="nativescript-label-marquee" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-label-marquee" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>
